font_family      Hack Nerd Font Mono

font_size 16.0
macos_thicken_font 0.0

background #0a0e14
foreground #b3b1ad
cursor #ffcc66
selection_background #161f2a
color0 #000000
color8 #686868
color1 #f07178
color9 #f07178
color2 #c2d94c
color10 #c2d94c
color3 #ffb454
color11 #ffb454
color4 #59c2ff
color12 #59c2ff
color5 #ffee99
color13 #ffee99
color6 #95e6cb
color14 #95e6cb
color7 #c7c7c7
color15 #ffffff
selection_foreground #2e333c
