[tools]
go = "latest"
java = "zulu-17"
python = "3.12"
node = "22.2.0"

"go:golang.org/x/tools/gopls" = "latest"

[settings]
experimental = true

[env]
MISE_NODE_COREPACK = 1
MISE_NODE_DEFAULT_PACKAGES_FILE = "{{env.HOME}}/.config/mise/default-packages/node"
