#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m space 1 --label browser
yabai -m space 2 --label terminals
yabai -m space 3 --label ides
yabai -m space 4 --label temp
yabai -m space 5 --label social
yabai -m space 6 --label music
yabai -m space 7 --label meetings
yabai -m space 8 --label calendar
yabai -m space 9 --label mail
yabai -m space 10 --label temp2

# global settings
yabai -m config                               \
	mouse_follows_focus          off            \
	focus_follows_mouse          off            \
	window_origin_display        default        \
	window_placement             second_child   \
	window_topmost               off            \
	window_shadow                off            \
	window_animation_duration    0.0            \
	window_opacity               on             \
	window_opacity_duration      0.15           \
	active_window_opacity        1.0            \
	normal_window_opacity        0.95           \
	insert_feedback_color        0xaaf7768e     \
	split_ratio                  0.50           \
	auto_balance                 off            \
	mouse_modifier               ctrl           \
	mouse_action1                move           \
	mouse_action2                resize         \
	mouse_drop_action            swap           \
	layout                       bsp            \
	top_padding                  12             \
	bottom_padding               12             \
	left_padding                 12             \
	right_padding                12             \
	window_gap                   6              
  # external_bar                 all:48:0

# yabai -m config --space ides layout stack

yabai -m rule --add app='^Slack$'            space=social
yabai -m rule --add app='^WhatsApp$'         space=social
yabai -m rule --add app='^Spotify$'          space=music
yabai -m rule --add app='^Music$'            space=music
yabai -m rule --add app='^zoom.us$'          space=meetings
yabai -m rule --add app='^Cron$'             space=calendar
yabai -m rule --add app='^Notion Calendar$'  space=calendar
yabai -m rule --add app='^Mail$'             space=mail

yabai -m signal --add event=application_launched app='^(Slack|WhatsApp)$' \
	action="yabai -m space --focus social"

yabai -m signal --add event=application_launched app='^(Spotify|Music)$' \
	action="yabai -m space --focus music"

yabai -m signal --add event=application_launched app='^zoom.us$' \
	action="yabai -m space --focus meetings"

yabai -m signal --add event=application_launched app='^Cron$' \
	action="yabai -m space --focus calendar"

yabai -m signal --add event=application_launched app='^Mail$' \
	action="yabai -m space --focus mail"

# apps to not manage (ignore)
yabai -m rule --add title='Updating '             manage=off
yabai -m rule --add title='^Slack \| mini panel$' manage=off
yabai -m rule --add app="^System Settings$"       manage=off
yabai -m rule --add app="^Logi Options$"          manage=off
# yabai -m rule --add app='^zoom.us$'               border=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add title="JetBrains Toolbox" manage=off mouse_follows_focus=off

echo "yabai configuration loaded.."
